<?php

namespace TestBlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticles()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT a
            FROM TestBlogBundle:Article a            
        ');
        $query->setMaxResults(3);
        return $query->getResult();
    }

    public function getMoreArticles()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT a
            FROM TestBlogBundle:Article a            
        ');
        $query->setFirstResult(3);
        return $query->getResult();
    }

}
